### ISSUE TITLE
updating prisma to 5.11 and using the experimental flag is showing a type error 

### ISSUE THREAD

**Issue by MSturges** [ajmnz/prisma-import#102]
```
generator client {
provider = "prisma-client-js"
previewFeatures = ["relationJoins"]
}
```
gives me the following type error `The preview feature "relationJoins" is not known. Expected one of: fullTextSearch, fullTextIndex, tracing, metrics, multiSchema, fieldReference, postgresqlExtensions, deno, extendedWhereUnique, views, jsonProtocol`

**Comment by ajmnz** [comment]
Hi, CI was broken and new versions were not being released.

Updating the extension to 5.11.0 will resolve the issue.

![Screenshot 2024-03-15 at 09 04 23](https://github.com/ajmnz/prisma-import/assets/57961822/24a0487b-918c-4232-bfbd-cbe7cb5083f1)

**Comment by MSturges** [comment]
Awesome sauce got the update this morning, works as expected!  Nice Work!
