### ISSUE TITLE
Extra line ending on format

### ISSUE THREAD

**Issue by Abror4544** [ajmnz/prisma-import#19]
When you using the extension VS Code and format the file, 1 extra line ending is being added
![image](https://user-images.githubusercontent.com/70596977/210262187-7785c18c-89ea-41a7-9516-9d948340139b.png)

**Comment by ajmnz** [comment]
Hi @Abror4544, I can reproduce this issue. Will get it fixed in the next release.

**Comment by ajmnz** [comment]
Fixed via #23 and will be available in the next release
