### ISSUE TITLE
Unexpected error on main file which defines datasource

### ISSUE THREAD

**Issue by Abror4544** [ajmnz/prisma-import#25]
![1](https://user-images.githubusercontent.com/70596977/211493088-cf4d11fd-108a-4003-b8c0-12af7f297594.png)

All my models in separate folder while my main prisma file which defines datasource in separate sibling directory. When I open main file extension shows such error.

```Error validating datasource `db`: You defined more than one datasource. This is not allowed yet because support for multiple databases has not been implemented yet.```

**Comment by ajmnz** [comment]
Hi,

You should configure the `prisma.import.exclude` option in your VSCode settings to exclude some schemas from being picked up. This accepts an array of glob patterns, relative to your workspace root.

You have to take into account that the extension combines all schemas virtually, so there should only be one datasource within all the files being picked up.

If the issue persists, let me know.

**Comment by ajmnz** [comment]
Please reload the vscode window after setting the `prisma.import.exclude` option (<kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> --> `Developer: Reload Window`)

**Comment by Abror4544** [comment]
Thanks, it worked.
