### ISSUE TITLE
Using 1.0.4 - Appends to file rather than truncating...

### ISSUE THREAD

**Issue by paulm17** [ajmnz/prisma-import#26]
This is a great project, so let me thank you again for taking the time to develop it!  🚀 

With the following prompt: 

> ✔ This will overwrite your output schema. You can disable this prompt with the --force option. Continue?

I was expecting that the file would be truncated and then appended to.  

Unfortunately, I'm not seeing the truncate, only an append.  So everything is duplicated.

Hopefully this isn't just me and you can replicate?  

Many thanks!

**Comment by ajmnz** [comment]
What might be happening is that the CLI is also picking up your output schema. Try specifying your schemas location either by passing a glob pattern to the `--schemas` option or setting it in your package.json like so:

```json
"prisma": {
    "import": {
      "schemas": "src/schemas/**/*.prisma",
      "output": "src/schema.prisma"
    }
  }
```

**Comment by paulm17** [comment]
Yes you were right.  I moved the models to a lower directory and this solved my problem.  Thanks!
