### ISSUE TITLE
Command for merging in VSCode

### ISSUE THREAD

**Issue by Peterculazh** [ajmnz/prisma-import#32]
Hello, I'm trying out with your extension. In description at marketplace there two ways of merging schemas into one and I pick with the running command in VSCode, but apparently there no such command for merging. 
For `Prisma` is available only three commands.
![image](https://user-images.githubusercontent.com/26142889/216765929-51ad9780-fb93-462f-91d1-1215fb261ecf.png)

The official extension were removed and restarted app few times.
To be mentioned, I'm using Windows 10, but not sure that this causes the problem

**Comment by ajmnz** [comment]
Hi @Peterculazh

I think I messed up there, so sorry for that. I added it to the README just as a to-do for myself, but never ended up adding the command.

While I will eventually add it, for now the merging should be done via our CLI package [prisma-import](https://www.npmjs.com/package/prisma-import). It's pretty simple to use and there are instructions on the package's README or via the `--help` flag, but if there's anything I can help you with, let me know.

**Comment by Peterculazh** [comment]
@ajmnz 
I got it :)
Installed CLI package
So firstly I run `npx prisma-import --schemas **/*.prisma` (and pressed Y as to force overwrite) and got updated only main schema `schema.prisma`, next run `npx prisma-import --schemas **/**/*.prisma` and got merged that my first model correctly, but then I updated model and run last command once again and got in schema a duplicate for my model, is it correct behavior or I'm doing wrong?
I just thought that package just keeps settings for connection and rewrites all after it
```//
// Autogenerated by `prisma-import`
// Any modifications will be overwritten on subsequent runs.
//

//
// schema.prisma
//

//
// Autogenerated by `prisma-import`
// Any modifications will be overwritten on subsequent runs.
//

//
// schema.prisma
//

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

//
// compliment.model.prisma
//

model Compliment {
  id   String @id
  text String
}

//
// compliment.model.prisma
//

model Compliment {
  id      String @id
  text    String
  message String
}

```
There is result

**Comment by ajmnz** [comment]
The problem is that the glob you pass to `--schemas` is also including your output `schema.prisma` and thus duplicating everything. You should exclude it from being picked up, ie.:

Output: `/prisma/schema.prisma`
Models: `/prisma/models/*.prisma`
Command: `prisma-import --schemas prisma/models/*.prisma --output prisma/schema.prisma`

**Comment by Peterculazh** [comment]
Thanks!
Is there a way to keep connection's settings from rewriting or should I make another schema for settings?

**Comment by ajmnz** [comment]
Absolutely, I usually keep a schema named `index.schema` where I have datasources and generators

**Comment by Peterculazh** [comment]
Awesome, thanks for help!
