### ISSUE TITLE
Unable to run on linux

### ISSUE THREAD

**Issue by scrap** [ajmnz/prisma-import#33]
I'm using Ubuntu 22.04, when trying to run `prisma-import --schemas ./prisma/schemas/*.prisma --output ./prisma/schema.prisma` I'm hit with 

`Error: Provide an output path. Either pass it with --output or add it to your package.json at prisma.import.output`

But the same command above works perfectly fine when running it on windows. Am I doing something wrong?

**Comment by ajmnz** [comment]
Looks like you might need to wrap your paths in quotes. Just pulled an Ubuntu 22.04 image, recreated more or less your directory structure and ran de following:

```shell
root@7bf9df4ddb8c:~# npx prisma-import --schemas ./prisma/schemas/*.prisma --output ./prisma/schema.prisma
/root/.npm/_npx/56402732312c327d/node_modules/prisma-import/dist/index.js:80
        throw new Error('Provide an output path. Either pass it with `--output` or add it to your package.json at `prisma.import.output`');
              ^

Error: Provide an output path. Either pass it with `--output` or add it to your package.json at `prisma.import.output`
    at /root/.npm/_npx/56402732312c327d/node_modules/prisma-import/dist/index.js:80:15
    at Generator.next (<anonymous>)
    at fulfilled (/root/.npm/_npx/56402732312c327d/node_modules/prisma-import/dist/index.js:6:58)


root@7bf9df4ddb8c:~# npx prisma-import --schemas './prisma/schemas/*.prisma' --output './prisma/schema.prisma'
✔ This will overwrite your output schema. You can disable this prompt with the --force option. Continue? … yes
root@7bf9df4ddb8c:~#
root@7bf9df4ddb8c:~#
```

Let me know if `npx prisma-import --schemas './prisma/schemas/*.prisma' --output './prisma/schema.prisma'` works!

**Comment by scrap** [comment]
Awesome! It indeed did work, thanks so much for the quick response, and library! 🙂
