### ISSUE TITLE
(feature/bug) Using native db types in nested models

### ISSUE THREAD

**Issue by bintoll** [ajmnz/prisma-import#4]
Hello! First of all I would like to say that this plugin could be really handy, thanks for it!
Looks like currently it is not possible to use native db types in nested models without getting error in vscode. 
That is because for example native type @db.Uuid in some nested file should refer to db datasource section, which is in root schema.prisma file so without importing it in nested file is an error in vscode ("Native type Uuid is not supported for Default connector."), but after importing it the error in root  schema.prisma the other error shows up because plugin thinks that db datasource was defined twice ("You defined more than one datasource"). 
Also regrading cli command - looks like there is no need to use glob pattern to include all schemas, if the imports are strictly declared and have a relative paths the paths to nested schemas could be resolved from parent schema path. As for now looks like it does not matter wether the nested file was imported or not it would anyway be merged based on glob pattern.

UPD: One more thing spotted, if there is already merged schema in the scope of glob pattern then this schema also would be included in the result one (with force flag enabled). Looks like the force flag should delete the previous result by the output file path or exclude it from the result of the search by glob pattern.

**Comment by ajmnz** [comment]
> Looks like currently it is not possible to use native db types in nested models without getting error in vscode.
> That is because for example native type @db.Uuid in some nested file should refer to db datasource section, which is in root schema.prisma file so without importing it in nested file is an error in vscode ("Native type Uuid is not supported for Default connector."), but after importing it the error in root schema.prisma the other error shows up because plugin thinks that db datasource was defined twice ("You defined more than one datasource").

I'm not sure I understood correctly the issue, but the extension automatically picks up the first `datasource` block it finds and there's no need to import it. What I usually do is have a `index.prisma` file that only declares the `datasource` and `generator`, and the extension takes it into account without having to do anything.


> Also regrading cli command - looks like there is no need to use glob pattern to include all schemas, if the imports are strictly declared and have a relative paths the paths to nested schemas could be resolved from parent schema path. As for now looks like it does not matter wether the nested file was imported or not it would anyway be merged based on glob pattern.

I thought about this when writing the CLI, but I finally decided that all schemas should be taken into account. This is because there's no such thing as an index schema, and thus there might be schemas that are not imported anywhere, but should still be merged.

> UPD: One more thing spotted, if there is already merged schema in the scope of glob pattern then this schema also would be included in the result one (with force flag enabled). Looks like the force flag should delete the previous result by the output file path or exclude it from the result of the search by glob pattern.

I can reproduce this. What I'll probably do is exclude the output path, or add a new flag to exclude multiple schemas from being picked up. Will that work?

**Comment by bintoll** [comment]
Thank you for such a fast response!
> I'm not sure I understood correctly the issue, but the extension automatically picks up the first datasource block it finds and there's no need to import it. What I usually do is have a index.prisma file that only declares the datasource and generator, and the extension takes it into account without having to do anything.
I mean a little bit different thing. According to prisma documentation it is possible to use database native types for example: @db.Uuid here are more:
<img width="699" alt="Снимок экрана 2022-12-25 в 22 04 40" src="https://user-images.githubusercontent.com/20185572/209470963-ab1582cd-6d32-4289-8919-aefe44a61ac7.png">
(https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference)
These types all are prefixed with "db" which means they reference datasource db (because native database data types differs for each database provider). So the datasource db should be in scope of the file if some of these types is used otherwise there would be an error.

>  thought about this when writing the CLI, but I finally decided that all schemas should be taken into account. This is because there's no such thing as an index schema, and thus there might be schemas that are not imported anywhere, but should still be merged.
Got it, sorry but for me it looks inconsistent. If there is the import syntax why should all the files be merged even those which were not imported explicitly? And the explicit syntax much more predictive. (imagine that javascript would import automatically all files from src directory rather than following import/export declarations).

> I can reproduce this. What I'll probably do is exclude the output path, or add a new flag to exclude multiple schemas from being picked up. Will that work?
I think excluding output path would work nice. Can not imagine any situation when it will be needed to pick file from output path again in merge process.

**Comment by ajmnz** [comment]
> So the datasource db should be in scope of the file if some of these types is used otherwise there would be an error.

You're right. A schema without imports would not get the virtual schema appended and thus no `datasource` would be in scope, leading to Prisma falling back to the default connector. With #6, the extension will take into account the first found `datasource` within all your schemas and make it available in the current opened file scope.

**Comment by ajmnz** [comment]
> Got it, sorry but for me it looks inconsistent. If there is the import syntax why should all the files be merged even those which were not imported explicitly? And the explicit syntax much more predictive. (imagine that javascript would import automatically all files from src directory rather than following import/export declarations).

I had this same debate when writing all this. It is indeed inconsistent, since it makes imports kind of useless, but I find much more painful having to declare in an "index file" which schemas are used and which are not. At the end of the day, in what case would you have a schema laying down your project that you don't want to use? Plus, forcing users to declare an index schema is a way more opinionated approach, which I wanted to avoid.

**Comment by bintoll** [comment]
Thanks for the fix, incredibly fast! =)

Okay, sure, it is up to you) 
Three points regrading 

>  forcing users to declare an index schema is a way more opinionated approach

1. There should be anyway some kind of an index.prisma/config.prisma/main.prisma as long as prisma requires to decelerate "generator client" and "datasource db" and if you keep declarations  of the models in separate files (as per idea of this plugin) you probably would not like to place this configuration things somewhere else, so the good place for it could be an entrypoint for imports of prisma files and it will fit the idea of import nice. (You also mentioned that you usually have index.prisma in previous message)
2. Again I would refer to javascript files resolution - mostly everyone is familiar with this approach having index.js as entry point. (It is actually common to have entrypoint in most of programming languages)
3. "At the end of the day, in what case would you have a schema laying down your project that you don't want to use?" - This actually could happen from time to time in some cases there is a good reason for that and in some cases not. I would refer here again to any other programming language with import/export declarations.

I would close this topic with this comment, as long as the main issue was fixed, the discussion about import resolution is more like a proposal and our opinions regarding this topic is clear, feel free to reopen if needed =)
