### ISSUE TITLE
Native database type attributes raise errors in VS Code extension

### ISSUE THREAD

**Issue by DanielleHuisman** [ajmnz/prisma-import#49]
I'm using Prisma Import CLI and the VS Code extension and love it so far, but I ran into a minor issue. I'm trying to use the [`@db.Uuid` attribute](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#postgresql) for a PostgreSQL database, so it uses the native `uuid` type. Unfortunately, the VS Code extension raises the following error:
> Native type Uuid is not supported for sqlite connector.

Is there any way I can specify the datasource provider in the extension? For the CLI part I have a `base.prisma` schema, so it works fine in the generated schema, but it would be even better if the extension didn't show errors for these attributes.

**Relevant files**

`prisma/base.prisma`:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["jsonProtocol"]
}

datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("DATABASE_SHADOW_URL")
}
```

`src/models/User.prisma`:
```prisma
model User {
    id       String @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
}
```

`package.json`
```json
{
    "scripts": {
         "prisma": "prisma-import -f -s '{prisma/base.prisma,src/**/*.prisma}' -o prisma/schema.prisma && prisma"
     }
}
```

**Comment by ajmnz** [comment]
👋🏼 @DanielleHuisman 

In theory the extension tries to find the datasource and generator blocks within all your schemas and injects them into whatever schema you've got opened, so this may in fact be a bug. 

Could you please share your OS, VS Code version and extension version?

**Comment by DanielleHuisman** [comment]
I'm using Ubuntu 22.10 with VS Code 1.77.3 and Prisma Import 4.13.101.

**Comment by ajmnz** [comment]
I can't seem to reproduce this with the following directory structure:

```
my-project
 ┣ prisma
 ┃ ┗ base.prisma
 ┗ src
 ┃ ┗ models
 ┃ ┃ ┗ User.prisma
```

Couple questions:
- Do you have by any chance `base.prisma` ignored via the `prisma.import.exclude` VS Code setting?
- Is `base.prisma` in the VS Code workspace? (ie. the folder you have opened contains all schemas)
- If you create a brand-new folder, open it with vscode and replicate the directory structure above, does the issue appear?

**Comment by DanielleHuisman** [comment]
Thanks, adding `**/schema.prisma` to the exclude settings fixes the the issue. You should probably add that to the VS Code documentation, so new users don't experience similar issues.

Alternatively, you could skip a `.prisma` file if it contains the Prisma Import header (```Autogenerated by `prisma-import``` ). That way there is no need for manually configuring the exclude pattern.

**Comment by DanielleHuisman** [comment]
I think you could add such a check in `setSchemasAndBlocksFromURIs` after reading the schema (around [here in the language server](https://github.com/ajmnz/prisma-import/blob/86f7088613/packages/language-server/src/imports.ts#L213)).

**Comment by ajmnz** [comment]
Awesome, glad we got it solved. I totally agree with your suggestions, so I opened #50 for docs and #51 for excluding the output schema by default. Thanks!
