### ISSUE TITLE
npx prisma-multischema error

### ISSUE THREAD

**Issue by febrimaulana** [ajmnz/prisma-import#74]
i running npx prisma-multischema and then result error
env: node\r: No such file or directory

whereas i running node -v is show
![image](https://github.com/ajmnz/prisma-import/assets/30101915/96f539a0-d28e-427e-a98f-8e2ea839d813)

**Comment by ajmnz** [comment]
This issue seems to be from a package called prisma-multischema, which has nothing to do with prisma-import
