### ISSUE TITLE
Necessary parts of the root schema are overwritten.

### ISSUE THREAD

**Issue by Bowis** [ajmnz/prisma-import#90]
I might be misunderstanding this, but this package has a major issue. A prisma schema always needs to have these additions:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```
But when i run the CLI this will always be overwritten... So what's the point even? The intellisense and importing is amazing but if this breaks it, its quite useless to me. What am i missing here?

**Comment by Bowis** [comment]
And now the glob pattern doesn't even work anymore, never mind this package. Horrible documentation, weird workflow, im looking for something else.

**Comment by ajmnz** [comment]
> What am i missing here?

Just create a `whatever.prisma` with your generators and datasources...

**Comment by ajmnz** [comment]
> And now the glob pattern doesn't even work anymore
> Horrible documentation, weird workflow

Feel free to contribute by opening a pull request with fixes, improvements and suggestions :)

**Comment by tazo90** [comment]
the following structure works for me great, thanks @ajmnz!

```
config.prisma
/models
 /user
  /user.prisma
 /organization
  /organization.prisma

```
